/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcEm1000pk0AnimQueryOrdersResponsePoutOrders implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("ORDSTS")
    private String ordsts;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("GMTSEQ")
    private String gmtseq;

    @ColumnAlias("GMTDES")
    private String gmtdes;

    @ColumnAlias("GARMENT")
    private String garment;

    @ColumnAlias("SSHPDAT")
    private LocalDateTime sshpdat;

    @ColumnAlias("QTYORD")
    private Integer qtyord;

    @ColumnAlias("CTYCOD")
    private String ctycod;

    @ColumnAlias("SAMEASQUERYORDER")
    private String sameasqueryorder;

    @ColumnAlias("BARCODENO")
    private String barcodeno;

    @ColumnAlias("CNT")
    private BigInteger cnt;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public String getOrdsts() {
        return this.ordsts;
    }

    public void setOrdsts(String ordsts) {
        this.ordsts = ordsts;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getGmtseq() {
        return this.gmtseq;
    }

    public void setGmtseq(String gmtseq) {
        this.gmtseq = gmtseq;
    }

    public String getGmtdes() {
        return this.gmtdes;
    }

    public void setGmtdes(String gmtdes) {
        this.gmtdes = gmtdes;
    }

    public String getGarment() {
        return this.garment;
    }

    public void setGarment(String garment) {
        this.garment = garment;
    }

    public LocalDateTime getSshpdat() {
        return this.sshpdat;
    }

    public void setSshpdat(LocalDateTime sshpdat) {
        this.sshpdat = sshpdat;
    }

    public Integer getQtyord() {
        return this.qtyord;
    }

    public void setQtyord(Integer qtyord) {
        this.qtyord = qtyord;
    }

    public String getCtycod() {
        return this.ctycod;
    }

    public void setCtycod(String ctycod) {
        this.ctycod = ctycod;
    }

    public String getSameasqueryorder() {
        return this.sameasqueryorder;
    }

    public void setSameasqueryorder(String sameasqueryorder) {
        this.sameasqueryorder = sameasqueryorder;
    }

    public String getBarcodeno() {
        return this.barcodeno;
    }

    public void setBarcodeno(String barcodeno) {
        this.barcodeno = barcodeno;
    }

    public BigInteger getCnt() {
        return this.cnt;
    }

    public void setCnt(BigInteger cnt) {
        this.cnt = cnt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcEm1000pk0AnimQueryOrdersResponsePoutOrders)) return false;
        final GetProcEm1000pk0AnimQueryOrdersResponsePoutOrders getProcEm1000pk0animQueryOrdersResponsePoutOrders = (GetProcEm1000pk0AnimQueryOrdersResponsePoutOrders) o;
        return Objects.equals(getOrdnum(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getOrdnum()) &&
                Objects.equals(getOrdsts(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getOrdsts()) &&
                Objects.equals(getClicod(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getClicod()) &&
                Objects.equals(getGmtseq(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getGmtseq()) &&
                Objects.equals(getGmtdes(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getGmtdes()) &&
                Objects.equals(getGarment(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getGarment()) &&
                Objects.equals(getSshpdat(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getSshpdat()) &&
                Objects.equals(getQtyord(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getQtyord()) &&
                Objects.equals(getCtycod(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getCtycod()) &&
                Objects.equals(getSameasqueryorder(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getSameasqueryorder()) &&
                Objects.equals(getBarcodeno(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getBarcodeno()) &&
                Objects.equals(getCnt(), getProcEm1000pk0animQueryOrdersResponsePoutOrders.getCnt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getOrdsts(),
                getClicod(),
                getGmtseq(),
                getGmtdes(),
                getGarment(),
                getSshpdat(),
                getQtyord(),
                getCtycod(),
                getSameasqueryorder(),
                getBarcodeno(),
                getCnt());
    }
}