/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcEm1000pk0AnimSltGrpResponsePoutSltGrp implements Serializable {


    @ColumnAlias("PROCESSGROUP")
    private String processgroup;

    @ColumnAlias("PROCESSGROUPDESC")
    private String processgroupdesc;

    public String getProcessgroup() {
        return this.processgroup;
    }

    public void setProcessgroup(String processgroup) {
        this.processgroup = processgroup;
    }

    public String getProcessgroupdesc() {
        return this.processgroupdesc;
    }

    public void setProcessgroupdesc(String processgroupdesc) {
        this.processgroupdesc = processgroupdesc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcEm1000pk0AnimSltGrpResponsePoutSltGrp)) return false;
        final GetProcEm1000pk0AnimSltGrpResponsePoutSltGrp getProcEm1000pk0animSltGrpResponsePoutSltGrp = (GetProcEm1000pk0AnimSltGrpResponsePoutSltGrp) o;
        return Objects.equals(getProcessgroup(), getProcEm1000pk0animSltGrpResponsePoutSltGrp.getProcessgroup()) &&
                Objects.equals(getProcessgroupdesc(), getProcEm1000pk0animSltGrpResponsePoutSltGrp.getProcessgroupdesc());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getProcessgroup(),
                getProcessgroupdesc());
    }
}