/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcEm1000pk0AnimQryAniCatlgResponsePoutAnimations implements Serializable {


    @ColumnAlias("TECID")
    private Long tecid;

    @ColumnAlias("TECHCODE")
    private String techcode;

    @ColumnAlias("TECHSEQ")
    private BigDecimal techseq;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("STYREF")
    private String styref;

    @ColumnAlias("LASTSAMPLEUSED")
    private String lastsampleused;

    @ColumnAlias("LASTORDERUSED")
    private String lastorderused;

    @ColumnAlias("PROPOSALOPTION")
    private String proposaloption;

    @ColumnAlias("RELDATE")
    private LocalDateTime reldate;

    @ColumnAlias("CNT")
    private BigDecimal cnt;

    public Long getTecid() {
        return this.tecid;
    }

    public void setTecid(Long tecid) {
        this.tecid = tecid;
    }

    public String getTechcode() {
        return this.techcode;
    }

    public void setTechcode(String techcode) {
        this.techcode = techcode;
    }

    public BigDecimal getTechseq() {
        return this.techseq;
    }

    public void setTechseq(BigDecimal techseq) {
        this.techseq = techseq;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getStyref() {
        return this.styref;
    }

    public void setStyref(String styref) {
        this.styref = styref;
    }

    public String getLastsampleused() {
        return this.lastsampleused;
    }

    public void setLastsampleused(String lastsampleused) {
        this.lastsampleused = lastsampleused;
    }

    public String getLastorderused() {
        return this.lastorderused;
    }

    public void setLastorderused(String lastorderused) {
        this.lastorderused = lastorderused;
    }

    public String getProposaloption() {
        return this.proposaloption;
    }

    public void setProposaloption(String proposaloption) {
        this.proposaloption = proposaloption;
    }

    public LocalDateTime getReldate() {
        return this.reldate;
    }

    public void setReldate(LocalDateTime reldate) {
        this.reldate = reldate;
    }

    public BigDecimal getCnt() {
        return this.cnt;
    }

    public void setCnt(BigDecimal cnt) {
        this.cnt = cnt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcEm1000pk0AnimQryAniCatlgResponsePoutAnimations)) return false;
        final GetProcEm1000pk0AnimQryAniCatlgResponsePoutAnimations getProcEm1000pk0animQryAniCatlgResponsePoutAnimations = (GetProcEm1000pk0AnimQryAniCatlgResponsePoutAnimations) o;
        return Objects.equals(getTecid(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getTecid()) &&
                Objects.equals(getTechcode(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getTechcode()) &&
                Objects.equals(getTechseq(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getTechseq()) &&
                Objects.equals(getClicod(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getClicod()) &&
                Objects.equals(getStyref(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getStyref()) &&
                Objects.equals(getLastsampleused(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getLastsampleused()) &&
                Objects.equals(getLastorderused(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getLastorderused()) &&
                Objects.equals(getProposaloption(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getProposaloption()) &&
                Objects.equals(getReldate(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getReldate()) &&
                Objects.equals(getCnt(), getProcEm1000pk0animQryAniCatlgResponsePoutAnimations.getCnt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTecid(),
                getTechcode(),
                getTechseq(),
                getClicod(),
                getStyref(),
                getLastsampleused(),
                getLastorderused(),
                getProposaloption(),
                getReldate(),
                getCnt());
    }
}