/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcEm1000pk0AnimSltThemeResponsePoutTheme implements Serializable {


    @ColumnAlias("PROCESSGROUP")
    private String processgroup;

    @ColumnAlias("SEQ")
    private Short seq;

    @ColumnAlias("THEME")
    private String theme;

    @ColumnAlias("INPBY")
    private String inpby;

    @ColumnAlias("INPDATE")
    private LocalDateTime inpdate;

    public String getProcessgroup() {
        return this.processgroup;
    }

    public void setProcessgroup(String processgroup) {
        this.processgroup = processgroup;
    }

    public Short getSeq() {
        return this.seq;
    }

    public void setSeq(Short seq) {
        this.seq = seq;
    }

    public String getTheme() {
        return this.theme;
    }

    public void setTheme(String theme) {
        this.theme = theme;
    }

    public String getInpby() {
        return this.inpby;
    }

    public void setInpby(String inpby) {
        this.inpby = inpby;
    }

    public LocalDateTime getInpdate() {
        return this.inpdate;
    }

    public void setInpdate(LocalDateTime inpdate) {
        this.inpdate = inpdate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcEm1000pk0AnimSltThemeResponsePoutTheme)) return false;
        final GetProcEm1000pk0AnimSltThemeResponsePoutTheme getProcEm1000pk0animSltThemeResponsePoutTheme = (GetProcEm1000pk0AnimSltThemeResponsePoutTheme) o;
        return Objects.equals(getProcessgroup(), getProcEm1000pk0animSltThemeResponsePoutTheme.getProcessgroup()) &&
                Objects.equals(getSeq(), getProcEm1000pk0animSltThemeResponsePoutTheme.getSeq()) &&
                Objects.equals(getTheme(), getProcEm1000pk0animSltThemeResponsePoutTheme.getTheme()) &&
                Objects.equals(getInpby(), getProcEm1000pk0animSltThemeResponsePoutTheme.getInpby()) &&
                Objects.equals(getInpdate(), getProcEm1000pk0animSltThemeResponsePoutTheme.getInpdate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getProcessgroup(),
                getSeq(),
                getTheme(),
                getInpby(),
                getInpdate());
    }
}