/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcEm1000pk0AnimRequestnosResponsePoutRequestnos implements Serializable {


    @ColumnAlias("REQUESTNO")
    private String requestno;

    @ColumnAlias("ITEMNO")
    private Byte itemno;

    @ColumnAlias("REQSTS")
    private String reqsts;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("GARMENT")
    private String garment;

    @ColumnAlias("RELDATE")
    private LocalDateTime reldate;

    @ColumnAlias("SMPCTYCOD")
    private String smpctycod;

    @ColumnAlias("SAMEASQUERYREQUESTNO")
    private String sameasqueryrequestno;

    @ColumnAlias("BARCODENO")
    private String barcodeno;

    @ColumnAlias("CNT")
    private BigInteger cnt;

    public String getRequestno() {
        return this.requestno;
    }

    public void setRequestno(String requestno) {
        this.requestno = requestno;
    }

    public Byte getItemno() {
        return this.itemno;
    }

    public void setItemno(Byte itemno) {
        this.itemno = itemno;
    }

    public String getReqsts() {
        return this.reqsts;
    }

    public void setReqsts(String reqsts) {
        this.reqsts = reqsts;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getGarment() {
        return this.garment;
    }

    public void setGarment(String garment) {
        this.garment = garment;
    }

    public LocalDateTime getReldate() {
        return this.reldate;
    }

    public void setReldate(LocalDateTime reldate) {
        this.reldate = reldate;
    }

    public String getSmpctycod() {
        return this.smpctycod;
    }

    public void setSmpctycod(String smpctycod) {
        this.smpctycod = smpctycod;
    }

    public String getSameasqueryrequestno() {
        return this.sameasqueryrequestno;
    }

    public void setSameasqueryrequestno(String sameasqueryrequestno) {
        this.sameasqueryrequestno = sameasqueryrequestno;
    }

    public String getBarcodeno() {
        return this.barcodeno;
    }

    public void setBarcodeno(String barcodeno) {
        this.barcodeno = barcodeno;
    }

    public BigInteger getCnt() {
        return this.cnt;
    }

    public void setCnt(BigInteger cnt) {
        this.cnt = cnt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcEm1000pk0AnimRequestnosResponsePoutRequestnos)) return false;
        final GetProcEm1000pk0AnimRequestnosResponsePoutRequestnos getProcEm1000pk0animRequestnosResponsePoutRequestnos = (GetProcEm1000pk0AnimRequestnosResponsePoutRequestnos) o;
        return Objects.equals(getRequestno(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getRequestno()) &&
                Objects.equals(getItemno(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getItemno()) &&
                Objects.equals(getReqsts(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getReqsts()) &&
                Objects.equals(getClicod(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getClicod()) &&
                Objects.equals(getGarment(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getGarment()) &&
                Objects.equals(getReldate(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getReldate()) &&
                Objects.equals(getSmpctycod(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getSmpctycod()) &&
                Objects.equals(getSameasqueryrequestno(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getSameasqueryrequestno()) &&
                Objects.equals(getBarcodeno(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getBarcodeno()) &&
                Objects.equals(getCnt(), getProcEm1000pk0animRequestnosResponsePoutRequestnos.getCnt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRequestno(),
                getItemno(),
                getReqsts(),
                getClicod(),
                getGarment(),
                getReldate(),
                getSmpctycod(),
                getSameasqueryrequestno(),
                getBarcodeno(),
                getCnt());
    }
}