/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcEm1000pk0AnimQueryDsgproposaloptionsResponsePoutSimilaritems implements Serializable {


    @ColumnAlias("DSGREQUESTNO")
    private String dsgrequestno;

    @ColumnAlias("SELECTIONSTS")
    private String selectionsts;

    @ColumnAlias("PROPOSALNO")
    private String proposalno;

    @ColumnAlias("PROPOSALOPTION")
    private String proposaloption;

    @ColumnAlias("DESIGNER")
    private String designer;

    @ColumnAlias("DSGTYPE")
    private String dsgtype;

    @ColumnAlias("THEMECATEGORY")
    private String themecategory;

    @ColumnAlias("GENERALTHEME")
    private String generaltheme;

    @ColumnAlias("SSNCOD")
    private String ssncod;

    @ColumnAlias("SAMEASQUERYOPTION")
    private String sameasqueryoption;

    @ColumnAlias("MIMETYPE")
    private String mimetype;

    @ColumnAlias("CNT")
    private BigInteger cnt;

    public String getDsgrequestno() {
        return this.dsgrequestno;
    }

    public void setDsgrequestno(String dsgrequestno) {
        this.dsgrequestno = dsgrequestno;
    }

    public String getSelectionsts() {
        return this.selectionsts;
    }

    public void setSelectionsts(String selectionsts) {
        this.selectionsts = selectionsts;
    }

    public String getProposalno() {
        return this.proposalno;
    }

    public void setProposalno(String proposalno) {
        this.proposalno = proposalno;
    }

    public String getProposaloption() {
        return this.proposaloption;
    }

    public void setProposaloption(String proposaloption) {
        this.proposaloption = proposaloption;
    }

    public String getDesigner() {
        return this.designer;
    }

    public void setDesigner(String designer) {
        this.designer = designer;
    }

    public String getDsgtype() {
        return this.dsgtype;
    }

    public void setDsgtype(String dsgtype) {
        this.dsgtype = dsgtype;
    }

    public String getThemecategory() {
        return this.themecategory;
    }

    public void setThemecategory(String themecategory) {
        this.themecategory = themecategory;
    }

    public String getGeneraltheme() {
        return this.generaltheme;
    }

    public void setGeneraltheme(String generaltheme) {
        this.generaltheme = generaltheme;
    }

    public String getSsncod() {
        return this.ssncod;
    }

    public void setSsncod(String ssncod) {
        this.ssncod = ssncod;
    }

    public String getSameasqueryoption() {
        return this.sameasqueryoption;
    }

    public void setSameasqueryoption(String sameasqueryoption) {
        this.sameasqueryoption = sameasqueryoption;
    }

    public String getMimetype() {
        return this.mimetype;
    }

    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    public BigInteger getCnt() {
        return this.cnt;
    }

    public void setCnt(BigInteger cnt) {
        this.cnt = cnt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcEm1000pk0AnimQueryDsgproposaloptionsResponsePoutSimilaritems)) return false;
        final GetProcEm1000pk0AnimQueryDsgproposaloptionsResponsePoutSimilaritems getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems = (GetProcEm1000pk0AnimQueryDsgproposaloptionsResponsePoutSimilaritems) o;
        return Objects.equals(getDsgrequestno(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getDsgrequestno()) &&
                Objects.equals(getSelectionsts(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getSelectionsts()) &&
                Objects.equals(getProposalno(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getProposalno()) &&
                Objects.equals(getProposaloption(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getProposaloption()) &&
                Objects.equals(getDesigner(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getDesigner()) &&
                Objects.equals(getDsgtype(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getDsgtype()) &&
                Objects.equals(getThemecategory(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getThemecategory()) &&
                Objects.equals(getGeneraltheme(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getGeneraltheme()) &&
                Objects.equals(getSsncod(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getSsncod()) &&
                Objects.equals(getSameasqueryoption(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getSameasqueryoption()) &&
                Objects.equals(getMimetype(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getMimetype()) &&
                Objects.equals(getCnt(), getProcEm1000pk0animQueryDsgproposaloptionsResponsePoutSimilaritems.getCnt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDsgrequestno(),
                getSelectionsts(),
                getProposalno(),
                getProposaloption(),
                getDesigner(),
                getDsgtype(),
                getThemecategory(),
                getGeneraltheme(),
                getSsncod(),
                getSameasqueryoption(),
                getMimetype(),
                getCnt());
    }
}