/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcEm1000pk0AnimAnimcodeUsageResponsePoutOrderlist implements Serializable {


    @ColumnAlias("REQUESTORDNUM")
    private String requestordnum;

    @ColumnAlias("CLICOD")
    private String clicod;

    @ColumnAlias("REQSTS")
    private String reqsts;

    @ColumnAlias("REQTYPE")
    private String reqtype;

    @ColumnAlias("SSHPDAT")
    private LocalDateTime sshpdat;

    @ColumnAlias("TECHCODE")
    private String techcode;

    @ColumnAlias("IMG")
    private String img;

    public String getRequestordnum() {
        return this.requestordnum;
    }

    public void setRequestordnum(String requestordnum) {
        this.requestordnum = requestordnum;
    }

    public String getClicod() {
        return this.clicod;
    }

    public void setClicod(String clicod) {
        this.clicod = clicod;
    }

    public String getReqsts() {
        return this.reqsts;
    }

    public void setReqsts(String reqsts) {
        this.reqsts = reqsts;
    }

    public String getReqtype() {
        return this.reqtype;
    }

    public void setReqtype(String reqtype) {
        this.reqtype = reqtype;
    }

    public LocalDateTime getSshpdat() {
        return this.sshpdat;
    }

    public void setSshpdat(LocalDateTime sshpdat) {
        this.sshpdat = sshpdat;
    }

    public String getTechcode() {
        return this.techcode;
    }

    public void setTechcode(String techcode) {
        this.techcode = techcode;
    }

    public String getImg() {
        return this.img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcEm1000pk0AnimAnimcodeUsageResponsePoutOrderlist)) return false;
        final GetProcEm1000pk0AnimAnimcodeUsageResponsePoutOrderlist getProcEm1000pk0animAnimcodeUsageResponsePoutOrderlist = (GetProcEm1000pk0AnimAnimcodeUsageResponsePoutOrderlist) o;
        return Objects.equals(getRequestordnum(), getProcEm1000pk0animAnimcodeUsageResponsePoutOrderlist.getRequestordnum()) &&
                Objects.equals(getClicod(), getProcEm1000pk0animAnimcodeUsageResponsePoutOrderlist.getClicod()) &&
                Objects.equals(getReqsts(), getProcEm1000pk0animAnimcodeUsageResponsePoutOrderlist.getReqsts()) &&
                Objects.equals(getReqtype(), getProcEm1000pk0animAnimcodeUsageResponsePoutOrderlist.getReqtype()) &&
                Objects.equals(getSshpdat(), getProcEm1000pk0animAnimcodeUsageResponsePoutOrderlist.getSshpdat()) &&
                Objects.equals(getTechcode(), getProcEm1000pk0animAnimcodeUsageResponsePoutOrderlist.getTechcode()) &&
                Objects.equals(getImg(), getProcEm1000pk0animAnimcodeUsageResponsePoutOrderlist.getImg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRequestordnum(),
                getClicod(),
                getReqsts(),
                getReqtype(),
                getSshpdat(),
                getTechcode(),
                getImg());
    }
}