/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;
import java.sql.Date;

import com.mu.cmt.pfs.pfsdb.models.procedure.*;

public interface PfsdbProcedureExecutorService {

    GetProcEm1000pk0AnimQueryDsgproposaloptionsResponse executeGetProcEM1000PK0_ANIM_query_dsgproposaloptions(String pprgid, String pdsgproposaloption);

    InputStream executeGetProcEM1000PK0_ANIM_ImgForMain(String ptechId);

    GetProcEm1000pk0AnimPrssCodResponse executeGetProcEM1000PK0_ANIM_PrssCod(String pprgid, String pgrp);

    InputStream executeGetProcEM1000PK0_ANIM_get_thumbnail(String pparam1, String pparam2);

    GetProcEm1000pk0AnimQueryOrdersResponse executeGetProcEM1000PK0_ANIM_query_orders(String pprgid, String ptechcode, Integer ptechseq, String pordnum);

    InputStream executeGetProcSY2110PK0_get_imagecardForOrder(String pprgid, String plibraryCat, String pdocid);

    GetProcEm1000pk0AnimQryAniCatlgResponse executeGetProcEM1000PK0_ANIM_QryAniCatlg(String pprgid, Date pdatefrom, Date pdateto, String ptechcode, String preference, String pclicod, String pusedinorder, String pprocesses, String pproposaloption, String pthemes, Integer pnoofcoloursfrom, Integer pnoofcoloursto, String pkeywords);

    GetProcEm1000pk0AnimSltGrpResponse executeGetProcEM1000PK0_ANIM_SltGrp(String pprgid);

    InputStream executeGetProcEM1000PK0_ANIM_ImgForPropOpt(String pdsgproposaloption);

    GetProcEm1000pk0AnimRequestnosResponse executeGetProcEM1000PK0_ANIM_Requestnos(String pprgid, String ptechcode, Integer ptechseq, String prequestno);

    GetProcEm1000pk0AnimAnimcodeUsageResponse executeGetProcEM1000PK0_ANIM_animcode_usage(String pprgid, String ptechcode);

    InputStream executeGetProcSY2110PK0_get_imagecardForPropOpt(String pprgid, String plibraryCat, String pdocid);

    InputStream executeGetProcSY2110PK0_get_ImagecardForSample(String pprgid, String plibraryCat, String pdocid);

    GetProcEm1000pk0AnimSltThemeResponse executeGetProcEM1000PK0_ANIM_SltTheme(String pprgid, String pgrp);

}